### ISSUE TITLE
Cannot Authenticate account

### ISSUE THREAD

**Issue by gmagdna** [TumblThreeApp/TumblThree#126]
Been using your software for years and love it. Never had a login issue until now...

I lost access to my Tumblr account because the 2FA codes generated in any one of my authentication apps were no longer accepted by Tumblr. They were no help so I had to start a new Tumblr account. In TumblThree when I enter the new Tumblr email and password and click Authenticate the button turns light grey briefly then back to darker grey. I've found several threads from the last few years about similar issues but none of the solutions work:

- cleared cache (I've tried Opera, Firefox, Edge, Chrome (shutdown TumblThree, cleared cache, restarted TumblThree)
- Run TumblThree from a new download of 1.8.8.76
- renamed all the files at Users\Username\AppData\Local\TumblThree\Settings except Queuelist and let TumblThree rebuild
- VPN and proxy are disabled
- edited User agent field to have only the browser I want to test. No issues logging into my Tumblr through the browsers

The blogs I previously connected to under the old Tumblr ID are showing Online or Offline, depending on the blog so TumblThree is connecting to the internet

Verified the Blog tab has selections checked (images and videos)

**Comment by thomas694** [comment]
You are using a quite outdated version (1.0.8.76, I assume a misspelling). Please use the newest version from [here](https://github.com/TumblThreeApp/TumblThree/releases).

Some posts and reviews in the internet describe the last version from our previous GitHub page. If you came from such a post, it would be nice if you send us the link to it (either here or by email).

**Comment by gmagdna** [comment]
I found the version to be the issue. I was previously running v.1.0.8.68. Within the software I went to About>Check for Updates and 1.0.8.76 downloaded, so I assumed it to be the most current version.

After continuing to research the issue I ran across v.1.0.12.1, downloaded and ran it and connected to Tumblr without a problem.

I also went back to my 1.0.8.76 and ran Check for Updates again and it still responded that I had the most current version.

**Comment by thomas694** [comment]
Of course, the version is the issue.

Let me try to explain it.
Last year the "home" of TumblThree changed from its old location to this one here.
As we cannot change/influence the url the TumblThree application is using for update searches of those already installed applications, they are searching and will forever search on the old location. There the most current version is and will be forever 1.0.8.76.

Only if the user wonders why there are no new versions for several months, or the login no longer works due to changes on the Tumblr site, some users are checking on the (old) TumblThree location. But they either oversee that the newest version there is already several months old or more important that on the main page it states "check out its new home: TumblThreeApp", or both.

You were lucky and found out how to open an issue in the new TumblThree location. We have shown you the new location of current and future versions. Now you know where to look in the future.

Welcome back!

**Comment by gmagdna** [comment]
Not luck that I found the new support location. I found it and the new/current download by diligent searching.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
