### ISSUE TITLE
🆕 Twitter blogs supported now!

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#161]
&nbsp;
:star: Besides the original Tumblr downloaders TumblThree has a **Twitter downloader** now! :tada:
&nbsp;
Just enter a blog url (e.g. https://twitter.com/cats :cat:) into the text field and add the blog to your list.

At the moment TumblThree can only download public blogs
and offers the following options:
* Download of photo, video and text posts of (public) blogs.
* Download meta information for photo and video posts.
* Allows to download only original content of the blog and skip reblogged posts.
* Can download only tagged posts.
* Allows to download blog posts in a defined time span.

Shall we keep this feature and maybe extend it in the future?
Please test it and send us your feedback and comments :pencil2: below!
Should you find a bug :bug: please open a new issue.

Enjoy this new feature in the next couple of days!
After several days we will get back and evaluate it.

<sub><sub>[#41]</sub></sub> <sub><sub>[#59]</sub></sub>

**Comment by cr1zydog** [comment]
Hello @thomas694 , i like this new Twitter feature. It works like a charm. I can download **pictures, videos, text** what Twint (_Only Text_) lacks.

But its text representation could be more effective with **twitter id, date, time** etc. as Twint does, otherwise it's a great tool to me.

_Thank you_ :)

**Comment by ztgasdf** [comment]
I agree wholeheartedly. You can also get the exact time of tweets by using something like https://github.com/oduwsdl/tweetedat without having to use the API.

**Comment by thomas694** [comment]
For starters we highly appreciate the feedback of the six people who have shown a reaction or given a feedback so far. :smiley:
/srs

It's not totally clear which of the numbers here on GH are suitable for measuring, e.g. how many people are using/downloading our application. The numbers are a bit divergent. :confused: But even in the best case calculation, an astonishing 1% :astonished: got their butt in gear and showed some reaction. :+1:

At the end we are sure we don't want to keep and maintain something that the majority of our users wants.
/s

**Comment by cewong2** [comment]
I just started trying this feature and it's great. is there a chance that we can add our "login" like the tumblr one so that we may access the protected twiiter accounts?

**Comment by thomas694** [comment]
It should be possible I think. But it will take some time.

**Comment by xathian** [comment]
Does this new feature actually download ENTIRE twitter feed history? There's been a well known issue with basically all Twitter downloaders for several years now about some sort of Twitter API restriction or throttle where downloads of Media posts (Picturess/Videos) simply will not go back to the accounts beginning if the account is older than a couple years. Most accounts will only download back around downloading posts for 1-2 years before cutting off.

This has killed off several Twitter downloaders because the devs simply couldn't get around it, you'd have 8 year old Twitter accounts that list as having, for example, 4500 Pic/Video posts but when you try to scrape them you get like 800 of the posts going back to 2019 then it just stops.

**Comment by thomas694** [comment]
The proof of the pudding is in the eating!
Or, to put it simply: Try it out.

**Comment by xathian** [comment]
> The proof of the pudding is in the eating! Or, to put it simply: Try it out.

Gave it a try, seems the answer is sort of 50/50. I tried on an account that has a total of 6503 media posts (https://i.imgur.com/Kedal6W.png) and the downloader managed to snag 5465 dating back to mid 2017. Still missing a considerable portion of the posts at over 1000 but this is a hell of a lot better than the alternatives which tend to flatline after ~2000 posts back to around late 2019.

This is pretty nice, probably the best Twitter downloader around right now. Hope you continue to support it.
