### ISSUE TITLE
Linux/Wine Support

### ISSUE THREAD

**Issue by ghost** [TumblThreeApp/TumblThree#163]
Interested in Linux/Wine support.

https://github.com/johanneszab/TumblThree/issues/62
https://github.com/johanneszab/TumblThree/issues/176

I haven't extensively reviewed what is broken for WINE support, but apart from waiting for Microsoft perhaps it would be easier to get working without the interface (so from commandline https://github.com/TumblThreeApp/TumblThree/issues/57)?

Thank you

**Comment by thomas694** [comment]
Hello,

the support for Linux/Wine (and Mac too) has been asked for only a couple of times in the past. So the user base needing it because they don't have Windows system available seems quite small. The amount of volunteers who like to contribute their time for testing and the like is even smaller. And it's quite difficult to find a developer in that small group who likes to contribute to our project. But you never know.

Maybe after updating our code base to .NET 5 there is a better support for other platforms. But we lack time and also some kind of knowledge on these platforms. Help is appreciated.

Related to the command line option, there hasn't been anybody yet who likes to implement something for it. Even for the more general (not developer related) task of writing down the required commands and options and a good naming of them, we haven't found volunteers yet.

Volunteers are welcome.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by aguazales** [comment]
Adding in case this can help anyone. I was able to get the latest 64-bit TumblThree release (v2.19.4 as of this writing) _mostly_ working on Linux Mint Cinnamon 22.3 using WINE and Winetricks. Currently not working for private blogs (things you have to be signed in to Tumblr to view). Did not test Twitter/Bluesky downloads.

**Steps I took:**
1. Downloaded the release archive from Github and extracted it to a folder
2. I used Winetricks to create a new wineprefix and added "dotnetcore3" and "dotnetcoredesktop3" to it via the "Install a Windows DLL or component" option.
3. I selected option "Run an arbitrary executable" and selected TumblThree.exe from the release archive folder
4. TumblThree launched but then complained that it couldn't find MicrosoftEdgeWebView2 library and offered to download it for me. Unfortunately Winetricks does not have a built-in option for this dependency, so I clicked yes and TumblThree opened the download in my browser.
5. I closed TumblThree, and then back in Winetricks I selected the "Run an arbitrary executable" option again, but this time I selected the MicrosoftEdgeWebView2Setup.exe that just downloaded; this ran and installed the last remaining dependency.
6. Once that finished, back in Winetricks I selected "Run an arbitrary executable" and selected TumblThree.exe from the release archive folder; this time it works when it launches.
7. I had to go to Settings --> General and change my download location because by default it was trying to save to somewhere read-only.
8. (optional) I created a shortcut/launcher on the desktop with the following command so I could launch TumblThree with a single click:`env WINEPREFIX="/home/user/.local/share/wineprefixes/tumblthree" wine /opt/TumblThree-x64/TumblThree.exe`

After that, I was able to add a Tumblr blog URL, adjust both global and blog-specific settings, and download posts successfully including images. The only thing that was not working (that I noticed) is the "AuthenticateView" window that opens when you try to sign in to Tumblr or Twitter or accept the Tumblr privacy consent; the login window popped up but stayed completely blank, so I was never able to sign in to Tumblr. When that happened the command line threw the following warning:
`libEGL warning: egl: failed to create dri2 screen`, but I'm not sure if that's related or a red herring. I did not test Twitter/Bluesky downloads because of the broken sign-in functionality.

Eventually I'll probably combine the unique wineprefix with the default one to save space, and I'd like to troubleshoot why it can't open the Tumblr sign in page (eventually, this already took me way too long lol). Assuming someone can get the sign-in working, maybe a community-contributed [Bottle](https://maintainers.usebottles.com/installers/Introduction) could be an option for 1-click installation of TumblThree on Linux? Not sure, might look into it at some point.
