### ISSUE TITLE
log in problem

### ISSUE THREAD

**Issue by papperdaemon** [TumblThreeApp/TumblThree#192]
**Expected Behaviour**

I expected to be able to log in

**Actual Behaviour**

A new window opened, a tumblr login window - I can successfully login there, but nothing happens after that and if I close it, no authentication is complete after that

**Steps to Reproduce the Problem**

Iog to settings -> connection and press "authenticate"

**Specifications**

I use the latest version, v2.4.4 and this problem wasn't present in previous versions 🤷‍♂️
win 10 ltsc
1809

**Comment by ImportTaste** [comment]
I don't think it's a problem specific to 2.4.4, I tried using an older version and it couldn't login either. I think something with Tumblr's website changed.

**Comment by thomas694** [comment]
I have good news and bad news.
The bad news, the login seems no longer to work.
But the good news, as the one or other may already have noticed, only the login status message isn't updated properly. After login you can use all functions as before.
They changed the account page that's why TumblThree can't find the information any more.

I think it can be fixed in the next version. Volunteers are welcome.

**Comment by ImportTaste** [comment]
> I have good news and bad news. The bad news, the login seems no longer to work. But the good news, as the one or other may already have noticed, only the login status message isn't updated properly. After login you can use all functions as before. They changed the account page that's why TumblThree can't find the information any more.
> 
> I think it can be fixed in the next version. Volunteers are welcome.

I do wish the [standard http cookie format](https://curl.se/docs/http-cookies.html) was used instead of what Cookies.json does, that way I could rather easily export cookies from my browser when things like this happen.

Right now I'm having to manually edit in values into the Cookies.json file, and it's tedious.

**Comment by thomas694** [comment]
I'm not sure what you are trying to do and why.
The current version verifiably still works, just log in as usual, then use anything that needs to be logged in (e.g. hidden blog). It works even it tells you in the settings dialog that you are still logged out.

In the rare case that you need to logout for some unknown reason, just delete the cookies file before starting.

**Comment by ImportTaste** [comment]
> I'm not sure what you are trying to do and why. The current version verifiably still works, just log in as usual, then use anything that needs you to be logged in (e.g. hidden blog). It works even it tells you in the settings dialog that you are still logged out.

Oh. I didn't really understand that from your previous reply. Now I get it, thanks.

**Comment by papperdaemon** [comment]
> I'm not sure what you are trying to do and why.

fine, why do we need the login function in the first place then?
are you saying its only needed for hidden or private blogs?

**Comment by ImportTaste** [comment]
> > I'm not sure what you are trying to do and why.
> 
> fine, why do we need the login function in the first place then? are you saying its only needed for hidden or private blogs?

He's saying that the login function is still working and that it's a visual/cosmetic bug.

**Comment by thomas694** [comment]
> He's saying that the login function is still working and that it's a visual/cosmetic bug.

That's right.
