### ISSUE TITLE
Tumblr video thumbnails

### ISSUE THREAD

**Issue by T-prog3** [TumblThreeApp/TumblThree#225]
As of now the new `Download video thumbnails` setting only works on Twitter blogs and not with Tumblr blogs. Tumblr videos still generates bonus thumbnails as default.

**Comment by thomas694** [comment]
It is as intended. As you might have already seen in the version announcement and option's tooltip it was done for Twitter blogs.

At the moment Tumblr video thumbnails are still downloaded, as all the years before. Also because it needs quite some more time to change it here. It might come in one of the next versions.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
