### ISSUE TITLE
No text post file, etc.

### ISSUE THREAD

**Issue by bloodconfetti** [TumblThreeApp/TumblThree#240]
**Expected Behaviour**

I expected, when downloading tumblrs, to have a .txt file inclusive of text posts and various other information. (I have it set to download all, except for external items such as giphy.)

I tried to authenticate (login) so that it would be able to download hidden Tumblrs.

**Actual Behaviour**

I only download images/videos and a .txt file called 'Videos'.

TumblThree crashed (the app disappeared/window closed itself) when I clicked 'Authenticate' in Settings.

**Steps to Reproduce the Problem**

Detail the steps below to help us reproduce the problem you encountered.

What it says on the tin. Pretty straight forward. I knew for a time TumblThree said it couldn't do text posts, but on the .io website, it says it does in the current version: "Download photo, video (only tumblr.com hosted), **text**, audio, quote, conversation, link and **question** posts." And yet it doesn't.

**Specifications**

Windows 10, TumblThree Version 2.6.2.309

**Comment by thomas694** [comment]
Hello,

although I was pretty sure, because I just did it a few days ago,
I just tried out a fresh installation of the current version and downloaded [apoemaday.tumblr.com](https://apoemaday.tumblr.com/) with the default settings. It downloaded 1308 text posts into a file texts.txt. Tried it again with the json option and it downloaded the same amount, only saved as json structure instead. So in general it works.

So the question is why you can't download text posts. Have you tried/checked the downloads of several blogs? None of them downloads any text posts? Have you used any other recent version in the past days? I'm asking because you mentioned that it was written that TumblThree cannot download text posts. That must be years ago.
You said that you have enabled all (except external image hosters) which should be the default settings and that it downloads images/videos. So the download is working and it should work for text posts too (if enabled). Have you already checked your settings again or tried it with a fresh installation (any remaining settings files are in "%LOCALAPPDATA%\TumblThree\Settings")?

As to your crash clicking on Authenticate, did you get a message on program start that it needs an additional package ([wiki](https://github.com/TumblThreeApp/TumblThree/wiki/Login%EF%BC%8FAuthenticate-does-not-work))? Have you extracted the zip file to a protected folder? You can have a look in our log file (%LOCALAPPDATA%\TumblThree\TumblThree.log) or the file debug.log inside the program folder, if you find a hint at the end of the file right after a crash happened.

**Comment by bloodconfetti** [comment]
Hi there! I'm so sorry... I'm an idiot. You're right. They are downloading. I guess I got confused looking at older versions, because the images now download (mostly) without 'tumblr' in front (is there a way to change that by the way? I'm trying to get rid of duplicate images so unfortunately the change of system is a little difficult) and those files used to be at the top of the folder rather than mixed in here and there. I apologize for taking up your time. I'll close this unless you want to respond to anything else.

**Comment by bloodconfetti** [comment]
Sorry I was rushing last time, because I was embarrassed about my mistake. But no, no message about needing an additional package, that I can see. Here's the debug log.
[debug.log](https://github.com/TumblThreeApp/TumblThree/files/8747072/debug.log)
.

**Comment by thomas694** [comment]
No worries, errors can happen. Everything is good.

Looking only in the log file I would say that not all files from the zip file are in the folder. It says it's missing a file resources.pak. Please extract the zip file into your TumblThree folder again.
But also make sure that the extra package is installed in your system.

**Comment by bloodconfetti** [comment]
Ohhh I wonder what happened lmao, okay well that fixed it! amazing!
