### ISSUE TITLE
False error when adding blogs

### ISSUE THREAD

**Issue by T-prog3** [TumblThreeApp/TumblThree#242]
Every new blog i add trigger the following message: `Error N: Could not add the blog: Exception 1`. Then it still adds the blog anyway so it's obvious a false positive error.

**Comment by thomas694** [comment]
It's good that you can reproduce it. Can you describe the steps before the error comes? I'm asking because something is special to your current installation/settings, not everyone gets this error and not so regularly.
Do you also get it when you add a blog right after starting the program or only after using it for some time? How many blogs are on your list, only a handful or far more?

**Comment by T-prog3** [comment]
I use all default settings, only thing that differ is `Activate portable mode`. There is no difference between adding a blog right after start or after some use, and i have about  25 blogs. But it appears as if you only can have one of these errors active. The first blog you add triggers the error, but adding a new blog after will not trigger another, unless you close the first error beforehand. So the error have a need to be triggered at all times to be in a happy state.

**Comment by Someonemustnothavethis** [comment]
I've been getting the same error every time I add a new blog.  My installation and settings are all default.  I do have around 300 blogs which might cause this.  It started 2 or 3 updates ago.   As with T-prog3, everything works perfectly despite the error message.

**Comment by thomas694** [comment]
The error should be solved.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
