### ISSUE TITLE
Tumblr: doesn't download all pictures of one posting

### ISSUE THREAD

**Issue by bloke90** [TumblThreeApp/TumblThree#329]
If the tumblr post consists of more than 5 (?) pictures (e.g. a gallery with 20 pics) only the first 5 pictures, rest is not downloaded.

Is this bug known? Is a fix possible?

**Comment by thomas694** [comment]
Maybe the others aren't downloaded, because the option "global duplicate check" is on and you already downloaded them before.
A photo(set) post can contain a maximum of 10 photos. If your mentioned post has more photos, than they maybe used some special theme and provided the data by some other means.
The download of standard photo(set) posts works without a problem.

If you send me the blog (non-safe one by email) and the link/time of the post, I'll check why it can't be downloaded.

**Comment by bloke90** [comment]
https://teensaremyfavorite.tumblr.com/ downloads only 5-6 pics each collection

**Comment by thomas694** [comment]
As already guessed they aren't photo posts, but text posts with html content. But anyways, all posts from august up to now were downloaded without problems.
Have you activated "global duplicate check" and a similar blog on your list?
Can you give me the date and time (no link) of a post that fails?

**Comment by thomas694** [comment]
If you still have problems downloading this blog, use the feedback dialog/page and send us the date/time or a link of an affected post.
