### ISSUE TITLE
Installation files zipped under TumbleThree sub folder, not TumblThree

### ISSUE THREAD

**Issue by ErikBrown2** [TumblThreeApp/TumblThree#39]
The installation zip file of the last few versions of TumblThree has the installation files packed under the sub folder TumbleThree, not under TumblThree as before. This means that if you unpack the installation files in the same folder as before, then a new installation folder will be created and the old files will not be overwritten. The blog folder will then also be changed. Is this done on purpose? If not, then it will be great if this can be fixed since the installation process will be easier.

In case you do not want to change the installation folder, is it possible for the users to manually install the files in the old TumblThree folder? Will all the old files be compatible with the new versions?

**Comment by gpriaulx** [comment]
This is completely my fault. I just assumed the alignment was close enough and not confusing. I will look at unifying that this weekend.

This has changed because previous builds were created by @johanneszab but current builds are built on AppVeyor, and I guess I was too careless with the packaging script to maintain uniformity. Sorry for the confusion.

You should be able to manually install the files in the old folder, everything should work as it did before really - nothing major has changed architecturally.

Stay tuned!

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
