### ISSUE TITLE
Current Release.

### ISSUE THREAD

**Issue by gpriaulx** [TumblThreeApp/TumblThree#4]
Create a new release of TumblThree, in its current state such that there is no need for consumers to interact with the existing TumblThree repository.

**Comment by johanneszab** [comment]
Do you think we should add anything before releasing a new release?

Issue wise, It might be nice to see the "liked/by" crawler fixed somewhat soon so that it's capable of downloading from https://www.tumblr.com/likes instead of just https://www.tumblr.com/liked/by/>>blogname<< as well as allowing it add blogs with the url path http://www.tumblr.com/blog/nature-e instead of just http://nature-e.tumblr.com/ using the blog as subdomain. That should at least restore the recently broken functionality and improve the usability for new users greatly. I'll make issue for both tomorrow.

We also need to change the the hard coded string in the [ApplicationUpdateService](https://github.com/TumblThreeApp/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Services/ApplicationUpdateService.cs#L39) and in the [About window](https://github.com/TumblThreeApp/TumblThree/blob/master/src/TumblThree/TumblThree.Presentation/Views/AboutView.xaml) before the new release.

**Comment by gpriaulx** [comment]
I agree. There are a few important issues. 
I like that the current milestone is mainly administrative and relatively small. It might be worth just knocking this petty stuff off over a week or so, and adding a new Milestone for some the existing pressing issues and features?

I'm fine either way - if you have no preference though, I will create (or you create) another milestone for a subset of the issues with the most value/importance and we can move on those over the coming weeks. 

I have a lot more free time through February to focus some effort here, and this would be a great way to get a better understanding of how everything is currently working.

**Comment by gpriaulx** [comment]
I have created the Milestone Renew Stability here: https://github.com/TumblThreeApp/TumblThree/milestone/2

**Comment by gpriaulx** [comment]
We really need to make a move on this. This is confusing some users. https://github.com/TumblThreeApp/TumblThree/issues/35

I'll pull across all the previous releases and do a quick functional test and release of the latest build today.

**Comment by gpriaulx** [comment]
I have pulled in the last 3 releases instead of all of them due to not having the same release branch and state as the original repository. I tagged the previous 3 releases against commits which occurred on the same day, but this may be incorrect. If this matters historically we should pull across the same commits and release branch. 

I'm not too concerned personally - new versions are where the excitement is!
