### ISSUE TITLE
Twitter Authenticate no longer work!

### ISSUE THREAD

**Issue by T-prog3** [TumblThreeApp/TumblThree#504]
There seem to have been some Twitter changes that made authentication to no longer work. It's just a blank window with an infinity refresh loop.

**Comment by thomas694** [comment]
At the moment it works again.

**Comment by T-prog3** [comment]
Yes, it appears to have been down only temporary during a week or so.

**Comment by T-prog3** [comment]
They have also implemented a new max posts per day limit where you get this message on their site.
`Unlock more posts by subscribing`
`You have reached the limit for seeing posts today. Subscribe to see more posts every day.`

**Comment by metapea** [comment]
For me [TumblThree](https://github.com/TumblThreeApp/TumblThree), auto removes the twitter authentication after when you login and save or exit the settings, but after that your still logged into twitter.
The downloader still works at least, but you will have to:
1. log in settings (for the first time)
2. exit the settings and download the twitter account
3. go to settings and authenticate twitter
4. exit the authenticate web browser, but don't exit settings 
5.  leave it there until the download ends
since twitter is still logged in, you can just open the authenticate browser and exit. then your twitter account will be authenticated

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
