### ISSUE TITLE
Use of old API doesn't display high resolution images

### ISSUE THREAD

**Issue by ShadowBlade72** [TumblThreeApp/TumblThree#51]
Yeah, the API limits are pretty high now for v2.  I'm not sure how the v1 requests look, as I was only looking at v2 and v2npf (neue post format).

It looks like most of Tumblr is switching to this neue (new) post format, which changes how they're displaying images.

As stated in the original issue, the image format changed from _1280 to embedding the resolution into the URL, as well as having a different URL for each resolution.  I've included two API calls below. One with the NPF flag for requests and one without.  From what I've seen, it's hit or miss as to which blogs have switched to the new format.  Some still use the _1280, while others are using the new format.

You'll see that with the npf=true you have different resolutions available.
Drill down to Response > Posts > 0 > Content > 0 > Media > {1,2,3,4,5,6,7}

Without npf=true the media is contained in the "body" tag and only shows up in 640x960 resolution.
Drill down to Response > Posts > 0 > Body

```
With NPF - http://api.tumblr.com/v2/blog/crazycatswiftie89.tumblr.com/posts?npf=true&id=186983242460&api_key={Insert your API key here}
Without NPF - http://api.tumblr.com/v2/blog/crazycatswiftie89.tumblr.com/posts?id=186983242460&api_key={Insert your API key here}
```

If this is confusing, let me know and I'll try to explain it better.

_Originally posted by @ShadowBlade72 in https://github.com/TumblThreeApp/TumblThree/pull/48#issuecomment-520916955_

**Comment by johanneszab** [comment]
Well, same problem as always.
I've looked for example images of "high resolution" images hosted on tumblr, I couldn't find any. That means larger than 1280px width or height as they are used to be.
Than I've uploaded a 8688x5792 image myself, and sure enough it was shrinked down to a size of 1280x853.

Can you show me any post with a lager image? Or extracted NPF data (i.e. text) with a link to a larger image?

Thus, I guess it's not worth switching at all.

**Comment by johanneszab** [comment]
Ah, i found it. Cool! It seems accessible via the SVC service as well. Than we don't need to mess around with API keys.

**Comment by KirbyFan102** [comment]
Hello, I just started using TumblThree, and I noticed that upon attempting to download all images from a certain blog, the 2048-sized ones weren't being downloaded. Which is a problem, because for some images, that's the ONLY size. I don't know if it's related to the above problem, but I thought you all should know. And I _am_ using tmblrpriv to download. So... any advice?

**Comment by johanneszab** [comment]
Hi there!

Thanks for using this issue! Please provide an example blog (or some other data), then I might look into it. Preferably a small one, else it might take me too long to understand what the issue is/you mean.
Since I don't use TumblThree myself anymore, I don't have any other ways to quickly identify what your problem is.

Alternatively, you're welcome to fix it yourself, in case of you want to commit code and investigate this issue.

**Comment by KirbyFan102** [comment]
Thank you for the reply. Here is the blog where I encountered the problem: https://jorrated.tumblr.com/tagged/myart

And for reference, here is one of the images the program didn't download: https://jorrated.tumblr.com/post/190690230056/sketch-commission-of-monokuma-and-monomis

In the above case, the program simply didn't download the image at all, but there were other instances where it downloaded 1280-sized versions as opposed to the largest file size. Thankfully, I had saved all images in this tumblr manually before discovering TumblThree, so I was able to easily notice any missing images.

**Comment by johanneszab** [comment]
First of all, thanks for proving all the necessary data needed in order to quickly investigate your issue.

However, for me it seemed to work. TumblThree downloaded [that image from your link](https://jorrated.tumblr.com/image/190690230056) with a size of 1829x1241 pixels.

In this screenshot, you can see all my settings:

![large_tumblr_image](https://user-images.githubusercontent.com/1684561/74103156-10382700-4b4a-11ea-980c-89514bfa8660.png)

Essentially, I've added the blog my copying it to the clipboard, then changed the "Crawler" to "tmblrpriv", then added the blog to the queue and started the download. Did you change the "image size" to "best" in the settings?

I know it's currently quite cumbersome to set up a simple blog download. I'm thinking of:

* only allow a single blog (tumblr / tumblrpriv) to be added. Currently, after changing the "Crawler", the same blog can be re-added wit the default crawler.
* Maybe there should be an option if you want per default all tumblr blogs to be crawled by the tumblrpriv (hidden/SVC) or the original Tumblr api v1 (tumblr) method.

**Comment by KirbyFan102** [comment]
Thank you! Changing the image size to best did the trick. (I also tested changing it to best and using the regular api, but it caused other images to be overlooked.) My own inexperience with the app was to blame in this case. Once again, thanks for the help. Sorry if I caused any trouble.

Also, I think I would like that second improvement you mentioned very, very much :)
