### ISSUE TITLE
Images saving as string of numbers instead of usual tumblr_XXX

### ISSUE THREAD

**Issue by noakai** [TumblThreeApp/TumblThree#56]
Tumblr seems to have changed how images are stored on their end, so instead of gifsets being saved by the program as:

tumblr_nmgkwurThj1sm6x1so1_500
tumblr_nmgkwurThj1sm6x1so2_500
tumblr_nmgkwurThj1sm6x1so3_500

It has been saving them as stuff like:

0c4f154aa27dd3268b23e6de64621d3141d293d6
0e4d30a891f94ccd9561a06d2aae4f9abcf6db4c

Even when they are the same gifset. Can anyone tell me if I can fix it on my end so the image sets at least stay together after they're saved?

**Comment by kyuber** [comment]
This is a problem I am also still having as well. Is there a way to fix this in the settings?

**Comment by thomas694** [comment]
Can you provide an appropiate example gifset post?
There is no fix yet.

**Comment by kyuber** [comment]
> Can you provide an appropiate example gifset post?
> There is no fix yet.

I'm not sure if this will be helpful, but the issue I'm having is the pictures in the photoset on the blog are saved as random strings of letters, which in turn has the photos spread on within the save folder, instead of beside each other. For the my purpose for these photos, it is extremely helpful to have the photos from the same post next to each other. When saving just a small amount of photos from a blog it is fine, but when saving the entire blog's photos, they become extremely hard to find with the way they are saved. In the past, an old tumblr image downloader I used saved the photos as tumblr_XXXXX (the X's being letters and numbers) but they kept all the photos from the same post together. I think this change to random strings of letters and numbers is tumblr's doing, so I'm not sure if there is an easy fix for this but it would be super helpful if there was one :( 

![2020-11-19 (1)](https://user-images.githubusercontent.com/74703977/99758115-7f1db580-2ab6-11eb-9b0c-7cd17392c3e1.png)
![2020-11-19](https://user-images.githubusercontent.com/74703977/99758116-7fb64c00-2ab6-11eb-9b88-e6d41776a48a.png)

**Comment by thomas694** [comment]
Thanks for the good example. I looked at the data source of this blog and at a post of it.
```
{
  "id": "635312356100063232",
  "url": "https://fytheboyz.tumblr.com/post/635312356100063232",
  "url-with-slug": "https://fytheboyz.tumblr.com/post/635312356100063232/wetheboyz-sangyeon-the-b-since-the-weather",
  "type": "photo",
  "date-gmt": "2020-11-20 14:04:36 GMT",
  "date": "Fri, 20 Nov 2020 23:04:36",
  ...,
  "photos": [
    {
      "offset": "o1",
      "photo-url-1280": "https://64.media.tumblr.com/182c56a732817d8bf92d8ce314be2f58/12b21f82838ffb5d-62/s1280x1920/df44bb2e653b9f2b3f59977fe9e6ad94a4be3ec9.jpg",
      ...
    },
    {
      "offset": "o2",
      "photo-url-1280": "https://64.media.tumblr.com/6027b37de4bc89a9f2570e10114956d7/12b21f82838ffb5d-32/s1280x1920/fbad1d5de3921e4a9f65814030f64de7b399c252.jpg",
      ...
    },
    {
      "offset": "o3",
      "photo-url-1280": "https://64.media.tumblr.com/16cddec35bfee7882bb1b2fe1e6e0076/12b21f82838ffb5d-40/s1280x1920/393101e237c4af7fe5b413354b35567dca0a1cb9.jpg",
      ...
    }
  ],
},
```
I left out the uninteresting parts. Maybe either this "group id" `12b21f82838ffb5d` or just the post id itself could be used to build filenames like
12b21f82838ffb5d_df44bb2e653b9f2b3f59977fe9e6ad94a4be3ec9.jpg
12b21f82838ffb5d_fbad1d5de3921e4a9f65814030f64de7b399c252.jpg
12b21f82838ffb5d_393101e237c4af7fe5b413354b35567dca0a1cb9.jpg
which would group images of one post together.

I still have to find and look at a real gifset, and also at the other media types. But i think at least the way with the post id could work with every post.

**Comment by thomas694** [comment]
For images Tumblr has at least two different url naming schemes, depending on the date the post was created originally. The old one where the filename part starts with `tumblr_` and ends with the image size class (e.g. `_1280`), additionally all image ids from one post have consecutive endings (tumblr_...o1_1280, tumblr_...o2_1280, ...). The new naming scheme is quite different. The image size class is encoded in the path (e.g. `/s1280x1920/`), all filenames have unique ids, but images from the same post don't have related filenames, only some part of the path contains an id that "groups together" the images of one post.

So in my opinion, it would be best to change the filenames of the saved images from `filename.jpg` to `{postId}_filename.jpg`. This would group images of one post together, also it would relate them more with the meta data which is downloaded as `{postId}.json`.
Other ideas or comments are welcome.

So we have to consider the different parts which need to be changed, keeping in mind already existing backups and so on.
The method `CheckIfFileExistsInDB(url)` checks if a file already has been downloaded by looking for the filename, the last part of the url, inside the blog's database file (e.g. `{blogname}_files.tumblr`). The method `CheckIfFileExistsInDirectory(url)` checks if the file already exists in the blog's folder. So both methods need the post id in addition and have a hit if either the old or new style of filenames is found.
To be consistent with the files in the folder, new files to the database should be added with the new naming style.
Finally the new filename has to be passed to the downloader too, so that after downloading the image is saved with the correct new filename.

Who wants to adapt the code?

**Comment by thomas694** [comment]
Since Tumblr introduced a new file naming scheme, which gives each file a unique guid, the images of one post are no longer side by side like before. Old files and blogs still have those old filenames starting with "tumblr_" which have a "group part" for photo sets.
There is a new option "group photo sets" in the settings. If a blog has this option enabled and a normal/reblogged post with a photo set that has new style filenames, the files are renamed.
When updating an old backup with the options "force rescan" and "group photo sets" enabled, already downloaded files with new style filenames are renamed.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
