### ISSUE TITLE
While using a tumbex URL not everything is downloaded.

### ISSUE THREAD

**Issue by Kvasmuppet** [TumblThreeApp/TumblThree#62]
When using a tumbex url not everything is downloaded. The cause of this is simple. Flagged posts are deleted by tumblr though the correct term should be "hidden" as said flagged post are still visible on tumbex and the image still exist on tumblr cdn's . This is my theory.

So when the application converts the tumbex url to a tumblr url, said "hidden" posts are not downloaded as they don't show up on the tumblr blog.

As it stands, the tumbex feature ,which was added because someone requested it so he or she could scrape those nsfw posts is not working and therefor pointless in it's current state. ( I think)

A solution would be to scrape tumbex directly instead of converting it to tumblr.

**Comment by johanneszab** [comment]
No example, no fix. Sorry. I don't have the time to search for an issue you might have seen without the steps to reproduce it.

I'm sure TumblThree even loads blogs Tumbex doesnt even display (404). Here, have two examples (NSFW):
https://www.tumbex.com/sexyperfectbodies.tumblr/posts
https://www.tumbex.com/h0t0rw0t.tumblr/posts

And if you read the other issue, I'm even saying there how Tumbex is apparently accessing the images, and how TumblThree does the same (depending on the chosen scraping implementation).

Thus, unless you are showing me a concrete example, I'll not do anything.
> [..] This is my theory.
> [..]
> therefor pointless in it's current state. ( I think)
> [..]
> A solution would be to scrape tumbex directly instead of converting it to tumblr.

Well, if you want that, feel free to submit the code.

To be honest, I'm really tired oh this kind of ($/"= posts. That's why this project is essentially dying. People are coming here, complaining, not even showing examples on how to reproduce those said errors, telling me how they would do everything better, yet are they even willing to actually contribute real code.

**Comment by johanneszab** [comment]
And for the record: I'm not even saying TumblThree is perfect, far from it! I'd even guess that Tumbex might show images TumblThree currently doesn't download just because of the big cluster f... which Tumblr is.

**Comment by Kvasmuppet** [comment]
And here we have an example of a developer who does not know how to properly respond to a user filing a github issue. If you want a reason as to why this project is dying (as you claim it is), here's probably why.

If you don't want people filing issues on your project, then don't put your project on Github. Good luck with it.

> Well, if you want that, feel free to submit the code.

I'm a user , not a dev. If I was a dev, I wouldn't be using this program now would I?

**Comment by johanneszab** [comment]
This is all so sad, sorry. Did I say that people should not open issues here? No! To all the rest, I'll simply not answer.

Good bye! Have a nice day.

**Comment by ErikBrown2** [comment]
> And here we have an example of a developer who does not know how to properly respond to a user filing a github issue. If you want a reason as to why this project is dying (as you claim it is), here's probably why.

Would it not have been better to thank the author for making such a great program?
