### ISSUE TITLE
SVC Crawler Sometimes Doesn't Get Full Resolution Images

### ISSUE THREAD

**Issue by MrBurgerKing** [TumblThreeApp/TumblThree#66]
For some reason the SVC Crawler downloads some images at 540 or lower, even if they are available at 1280.
For example, on [this post](https://nyx-chaos-nix.tumblr.com/post/611865788695068672/could-courage-say-something-positivity-related) SVC found the 540 version:
`https://66.media.tumblr.com/8fd7c78410baad22922c1f979e5c45b6/afe7ebb0102e1866-3a/s540x810/0d4adcf1ca8511376d8d5fe699f616be3477864e.jpg` 
but did not find the full quality 1280 version
`https://66.media.tumblr.com/8fd7c78410baad22922c1f979e5c45b6/afe7ebb0102e1866-3a/s1280x1920/0926daa27480a7e726df601b4559652ace3d86b2.jpg`

Search for image patterns and download specified size don't have any effect.
Setting the crawler to 1280 manually just caused it to download 1280 versions of 2048 images,

I've made sure my quality is set to best, I'm logged in, and the crawler is actually set to SVC.
Is there anything I'm forgetting or is this an issue/limitation of SVC?

![screen](https://user-images.githubusercontent.com/60558248/76277119-ced48d80-6255-11ea-9d8d-36e3ac867a1f.png)

**Comment by johanneszab** [comment]
No, you are doing everything correctly.

If you look at the attached example data taken from the blog of your screenshot, what we are currently doing if best is chosen in the image size settings is taking the [first image from the `alt_sizes` array](https://github.com/TumblThreeApp/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Crawler/TumblrHiddenCrawler.cs#L482):

~~~
"photos": [
	{
		"caption": "",
		"original_size": {
			"url": "https://66.media.tumblr.com/b5ea0cc7b102dc5e4efb0d7a8f011886/06839483cd173825-49/s1280x1920/4604aca68d2e5910153e3b00e25e31c1ca6a6b67.jpg",
			"width": 1280,
			"height": 1707
		},
		"alt_sizes": [
			{
				"url": "https://66.media.tumblr.com/b5ea0cc7b102dc5e4efb0d7a8f011886/06839483cd173825-49/s2048x3072/a2347a5f012015bdc424f93c4afbc63ff43c701c.jpg",
				"width": 2048,
				"height": 2731
			},
			{
[..]
~~~

I just briefly scanned through this data, and the first item was usually larger (i.e. a 2048px width image) or the same size as the `original_size` image.

The problem with this "full resolution/_raw" sizes is that they are some kind of an afterthought. All the other sizes are always available for all images, hence just selecting "2048px" might sometimes fail.

However, one could check if the size of the first element of the `alt_sizes` array is actually larger than the `original_size`, if yes, take that, otherwise keep the original. But I'm not sure if this is actually the case, that the first element of the `alt_size` is every smaller than the `original_size`.

[nyx-chaos-nix_svc-data.txt](https://github.com/TumblThreeApp/TumblThree/files/4313914/nyx-chaos-nix_svc-data.txt)

**Comment by MrBurgerKing** [comment]
Thanks for getting back to me!
Again, the issue is with some posts, but not others. If you look at the specific post I referenced above, the photo shown to the user on web (`0926daa27480a7e726df601b4559652ace3d86b2`) isn't present in the crawler dump.
I'm on mobile so I can't look through the data in depth yet, but this seems to be a problem with answer posts specifically. Answer posts don't have a `photoset` or `photos` array, only a 540 version of the image in HTML a few times.
So does Tumblr web make the svc request differently for answer posts? Or do they get the photo to show to the user some other way? I apologize for not being that familiar with the Tumblr api, but I'll experiment and try to figure out tonight.

**Comment by MrBurgerKing** [comment]
This looks like a limitation of the api. I'm not really sure how tumblr gets the full size image for answers in web view internally, but it's hard to tell since it is pre-rendered on the server side.
Either way, I was able to download what I needed manually.
Thanks for all the help!

**Comment by ImportTaste** [comment]
> No, you are doing everything correctly.
> 
> If you look at the attached example data taken from the blog of your screenshot, what we are currently doing if best is chosen in the image size settings is taking the [first image from the `alt_sizes` array](https://github.com/TumblThreeApp/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Crawler/TumblrHiddenCrawler.cs#L482):
> 
> ```
> "photos": [
> 	{
> 		"caption": "",
> 		"original_size": {
> 			"url": "https://66.media.tumblr.com/b5ea0cc7b102dc5e4efb0d7a8f011886/06839483cd173825-49/s1280x1920/4604aca68d2e5910153e3b00e25e31c1ca6a6b67.jpg",
> 			"width": 1280,
> 			"height": 1707
> 		},
> 		"alt_sizes": [
> 			{
> 				"url": "https://66.media.tumblr.com/b5ea0cc7b102dc5e4efb0d7a8f011886/06839483cd173825-49/s2048x3072/a2347a5f012015bdc424f93c4afbc63ff43c701c.jpg",
> 				"width": 2048,
> 				"height": 2731
> 			},
> 			{
> [..]
> ```
> 
> I just briefly scanned through this data, and the first item was usually larger (i.e. a 2048px width image) or the same size as the `original_size` image.
> 
> The problem with this "full resolution/_raw" sizes is that they are some kind of an afterthought. All the other sizes are always available for all images, hence just selecting "2048px" might sometimes fail.
> 
> However, one could check if the size of the first element of the `alt_sizes` array is actually larger than the `original_size`, if yes, take that, otherwise keep the original. But I'm not sure if this is actually the case, that the first element of the `alt_size` is every smaller than the `original_size`.
> 
> [nyx-chaos-nix_svc-data.txt](https://github.com/TumblThreeApp/TumblThree/files/4313914/nyx-chaos-nix_svc-data.txt)

It sounds like this would be a way to re-implment being able to download _raws, is this still being looked into?

**Comment by johanneszab** [comment]
Not sure what you mean exactly, but it's already implemented since Feburary. It doesn't work for answer posts however, because the data simply doesn't exist for those posts for some reason.

See this release notes information and the corresponding issues for more: https://github.com/TumblThreeApp/TumblThree/releases/tag/v1.0.11.5

**Comment by pakiec22** [comment]
I think it is still present, e.g. https://www.tumblr.com/betaboiseat4feet-blog
has this post
https://www.tumblr.com/betaboiseat4feet-blog/666787421031170048

And the pic can be downloaded 2-3 bigger by web.
either SVC or Api.
I can't achieve that using tumblrthree app.
The same, bigger size I mean.
It downloads like 540 width all the time
