### ISSUE TITLE
Individual blog settings (download location) not being saved.

### ISSUE THREAD

**Issue by Someonemustnothavethis** [TumblThreeApp/TumblThree#68]
I've created four blog lists (separated by subject) and have made four directories with subdirectories for each blog.  I save the list but when I open the list again, the settings panel is blank for each blog and when I set it to crawl and catch up with the blogs, everything gets downloaded to the default directory.
Is this a bug or am I doing something wrong?
It's still a brilliant program and I'd still love to send you twenty bucks.
Thanks a bunch!
Bob

**Comment by johanneszab** [comment]
I wouldn't do it like this. Try this:

Extract TumblThree, run it, go to the settings, perform the Tumblr login (and all the other settings you want to modify) and in the `Settings->General` tick `Activate portable mode`. Now close TumblThree. You'll end up with a correctly setup TumblThree and all necessary settings in that folder. You'll also see some new files like `Settings.json`, `Queuelist.json` popping up.

Now, You can duplicate this folder and run all instances of it separately, all of them with their own blog list. Since the binary is only a few KBs, the duplicating shouldn't be such a big issue. 

And a note on the export functionality: If you open the exported blog file (exported via Settings->General->Export Blogs), all what's in there are the Tumblr URLs, no settings. Hence, if you import those files, there are no settings for TumblThree to import.

You might also want to read the README.md. I've written a little about the `\Index\` folder there which is located in your `Download location` (default: \Blogs\Index\). This folder contains two json files per blog containing all the blogs settings and previously downloaded files. You could also move those to one of your newly created portable TumblThree instances to resume their state.

**Comment by Someonemustnothavethis** [comment]
Hi Johannes,
   Thanks for the reply.  It sounds like a lot of screwing around for
a non-techy-or-programmer, so I'm just making one
lo-o-o-ng list and hope for the best.
    I do have a question about 'Evaluating' blogs.  When I add a date
to 'download From' in 'Blog Settings', in the  
'Queue' it says that it's 'Evaluating' Tumblr posts.  This takes a
lo-o-o-o-ng time and can take overnight to complete 
several big blogs.  I get the impression it's checking every single
post for the date before downloading just the ones
after the specified date.  It's a lot faster to just start from the
beginning and download them all then it is what wait ages
for the 'Evaluation'.  Is this something that can be fixed, or is it
by design?
     Thanks again.
       Bob and his stupid Tumblr addiction.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
