### ISSUE TITLE
Downloading empty video files (TumblThree defaults to outdated TLS version on Windows 7).

### ISSUE THREAD

**Issue by KyleC69** [TumblThreeApp/TumblThree#74]
I have used your application for years and love it. Kudos. Recently however, it will download all other formats except videos. The filename gets created with the mp4 extension with 0 bytes.
I have tried many different versions from 8 forward with the same results. I have removed every trace of the application and started with an out of the box copy of the latest 1.0.11.6  I have deleted the user profile and started with a fresh profile with the same results. I'm out of ideas on where to look for problem. Where to look now for anomalies?

**Comment by bugzc** [comment]
Can confirm this happens. It's not just you.

**Comment by johanneszab** [comment]
Can you provide me (here, per mail) an example, non working, preferable small blog?
I've tested the next best "video" blog Tumblr suggested me (https://thesassyducks.tumblr.com/) and it seemed to be working fine however. Both, using the Tumblr API and the Tumblr SVC crawler:

![video_tumblthree_thesassyducks](https://user-images.githubusercontent.com/1684561/87386983-0b1c4f80-c5a2-11ea-8666-ed8e99fcaf25.jpg)

**Comment by KyleC69** [comment]
This is what I get when I add sassy duck example blog

Is there any logging or command line options I can use to get feedback? Threre are no errors shown in the gui.
![Capture](https://user-images.githubusercontent.com/68043041/87415564-1b243700-c582-11ea-8562-ddce241f4cf5.PNG)

**Comment by BiggRanger** [comment]
Same issue here too. Running version 1.0.8.74
Operating system: NT6.1.7601 SP1
.NET: 4.0.30319.42000 64 Bit

**Comment by KyleC69** [comment]
After stepping through the most recent code release, I have found that an exception occurs when the GetResponseAsync is fired in the DownloadFileWithResumeAsync method. An Error Event is sent to the System log EventID 36887 Source is SChannel Error 70. Any ideas on what might be causing this?

**Comment by mamift** [comment]
Hello, I'm getting this same issue. But I believe I found a fix. After this line: dfsad

**Comment by KyleC69** [comment]
Thank you mamift, that did the trick.

**Comment by johanneszab** [comment]
First of all, thanks a lot to you all for figuring this out!
I'd probably never have found this issue on my machine with Win10 and the latest .NET Framework as downloading videos seems to be without issues for me.

As for the issue: Man, this looks broken. I've assumed it would always try to get the most secure connection, as browser do in their TLS/SSL handshakes. But it looks like, after reading through these websites ([1](https://stackoverflow.com/questions/44751179/tls-1-2-not-negotiated-in-net-4-7-without-explicit-servicepointmanager-security), [2](https://github.com/dotnet/docs/issues/4675), [3](https://docs.microsoft.com/en-us/dotnet/framework/whats-new/#net47)), that it depends on your .NET Framework version, your OS, and then you can't even set it up to default to the most secure TLS version.

I assume you all are on Windows 7? After reading those sites, The default TLS OS version on Windows 7 is 1.0, and thats what you get if you don't specify any other version. That alone is horrendous.
I don't like the fix mamift suggests. It's a good one, for sure, and probably will last longer than TumblThree, but I'd like to have it setup to always pick the most recent version automatically, for all OS and .NET version, without having to modify the code if the TLS (or chipher) version changes.

Thats why I'd like to test changing the .config files instead. Can anyone with issues test this attached .zip file? It contains the .config files (e.g. TumblThree.exe.config) from TumblThree which have to replace the .config files in the TumblThree root directory. I only added
~~~
	<AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=true"/>
~~~
this line to them which should setup TumblThree to use the latest .NET Framework Standard TLS version (instead of relying on the default OS version).

It that doesn't work however, I'll add mamifts suggestion to the code and release a new version with that.

**Comment by BiggRanger** [comment]
Just tested with the files int he ZIP you posted, and it seems to be working fine now.

Running version 1.0.8.74
Operating system: NT6.1.7601 SP1
.NET: 4.0.30319.42000 64 Bit

**Comment by bugzc** [comment]
Working with the updated config files here too. 
TumblThree v1.0.11.6
Windows 7 [ 6.1.7601 Service Pack 1 Build 7601 ]
.NET v4.0.30319

**Comment by johanneszab** [comment]
Thanks for testing!

I've opted for the config variant and released a fixed version. I'll leave this issue open for a while. If there are still any issues with this, then we can still merge @mamift fix.

**Comment by ThomasFr42** [comment]
Since one week TumblThree recives only empty files (all types)
I use Vs 1.4.1.126 of TumblThree
Microsoft Windows NT 6.1.7601 SP1  (Win7)
The installed .Net Framework is 4.8
I deinstalled TumblThree several times and installed it again,also local/TumblThree
I deinstalled .Net Framework 4.8 and installed it again.
I imported Index from another PC (also Win7 with .Net Vs 4.8 succesfully running)
But TumblThree only crawls empty files of picture and *.mp4 and so on.

Here is the logfile

20210428 21:43:32.052	Inf 	IsLongPathSupported: False
20210428 21:45:08.285	Err 	AbstractCrawler.RequestDataAsync: System.Net.WebException: The request was aborted: The request was canceled.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at TumblThree.Applications.Services.WebRequestFactory.<ReadRequestToEnd2Async>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TumblThree.Applications.Crawler.AbstractCrawler.<RequestDataAsync>d__53.MoveNext()

No idea what is the reason of this error.

**Comment by ThomasFr42** [comment]
Check for Updates also fails.
The request was aborted; Could not create SSL/TLS secure channel.
Disabling virus scanner or Firewall doen't change the error

**Comment by thomas694** [comment]
Hello,
as you already mentioned on your other PC it runs successfully. So it's not an error by default.
Something changed on this PC in the last week. It's hard for us to guess what the problem is. TumblThree/Tumblr needs TLS 1.2 working.
I have a system with the same Win 7 configuration here, except it's 32 bit win. And I can only reproduce this error, if I remove the already above mentioned line from the config or set it to false.
~~~
	<AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=true"/>
~~~
So you have to find out what changed on your system in the last week. Does the Tumblr website work in your web browser?

**Comment by ThomasFr42** [comment]
I installed now TumblThree Vs.2.0.1.183 it still does not function anymore.

**Comment by ThomasFr42** [comment]
Unter the Button About i press Check for Updates. The message The request was aborted: Could not create SSL/TLS secure channel.
Virus Scanner MalwareByte and Zonealarm are disabled for this Test.

![grafik](https://user-images.githubusercontent.com/83372302/129481828-4d5b0acb-79f9-49ef-8bcd-8c524ec29d91.png)

**Comment by ThomasFr42** [comment]
Microsoft.Net Framework shows no filesize. On the other Win 7 Machines the is the same .Net Version installed,
but you can see the Size of .Net 4.8. On these machine TumblThree is running.
On the machine with the problem of "Could not create SSL/TLS .. i installed Microsoft Visual Studio 2019 - Community Edition.
Since that time i recognized the thumblthree error the first time.
I also uninstalled all .Net Versions and installed them new. Nothing helped.

**Comment by thomas694** [comment]
What are your values under 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.**3**\Client 
on the machine with the problems?
Please provide the values under the keys for TLS 1.1, 1.2 and 1.3.

**Comment by ThomasFr42** [comment]
Problem solved.
In the registry was no entry for TLS 1.2 or TLS 1.3.
Writing this Entry and restarting the PC solved the Problem.
TumblThree is running perfectly
Thank you Thomas694
