### ISSUE TITLE
Tumblr Searches (tumblr.com/search/ and tumblr.com/tagged/) Don't Work Anymore.

### ISSUE THREAD

**Issue by ErikBrown2** [TumblThreeApp/TumblThree#75]
The current version of TumblThree (1.0.11.7) and the previous version (1.0.11.6) frequently hang during downloads. Downloading stops and the only way to get it to download again is to restart TumblThree. It appears to only happen during downloads of tag searches. For instance for https://www.tumblr.com/tagged/lycrapavel

When the downloading hangs, the TumblThree interface still works fine. The tag search has become the top of the queue but it is not highlighted in blue yet. Also in the main left side table, the entry is still purple and not green yet.

When I exit TumblThree and restart it, then the queue will be as it was when I started crawling the previous time. When it reaches the tag search that caused it to hang before, then it will hang again. There are also some tag searches that did not cause the hanging. Not sure if this was relevant but these tag searches did not result in the download of a picture.

I am using Tumblr SVC.

**Comment by johanneszab** [comment]
Hi!

Thanks for opening this issue! I've already found the issue that's causing the crash, and looks like I've caused it in the 1.0.11.6 release during the implementation of the StreamWriter caches. 

However, after fixing this I've seen that zero posts will be downloaded in the tagged search you've provided. I've briefly looked into it, and it seems like Tumblr is now using its v2 API for its searches (tagged, and regular) on its website. This is a change. Previously, they returned a link within the html response with some generated key which you'd have to go to in order to get to the next page.

Now it looks like this:
When opening a tagged search as an authenticated user, you'll get a payload containing a Bearer Token for using their API v2 search endpoint. See this image of a request for the page https://www.tumblr.com/tagged/car.

![tumblr_tagged_car_search_developer_tools](https://user-images.githubusercontent.com/1684561/89121532-002d4e80-d4c0-11ea-9a69-112deadcefbd.jpg)

When opening `Response -> Respone Payload` in the Developer Tools, you'll notice some json embedded within the response :
[tumblr_tagged_car_search_response.txt](https://github.com/TumblThreeApp/TumblThree/files/5012022/tumblr_tagged_car_search_response.txt)
This contains all the images for the search, and the api v2 endpoint on how to continue with the search together with a pre-generated api v2 key:

```json
		"nextLink": {
			"href": "/v2/mobile/search/posts?fields%5Bblogs%5D=name%2Cavatar%2Ctitle%2Curl%2Cis_adult%2C%3Fis_member%2Cdescription_npf%2Cuuid%2Ccan_be_followed%2C%3Ffollowed%2C%3Fadvertiser_name&reblog_info=true&mode=recent&query=car&limit=20&blog_limit=0&post_offset=1595453234&post_limit=20",
			"method": "GET",
			"queryParams": {
				"fields": {
					"blogs": "name,avatar,title,url,is_adult,?is_member,description_npf,uuid,can_be_followed,?followed,?advertiser_name"
				},
				"reblogInfo": "true",
				"mode": "recent",
				"query": "car",
				"limit": "20",
				"blogLimit": "0",
				"postOffset": "1595453234",
				"postLimit": "20"
			}
		}
	},
	"apiUrl": "https://www.tumblr.com/api",
	"apiFetchStore": {
		"API_TOKEN": "aIcXSOoTtqrzR8L8YEIOmBeW94c3FmbSNSWAUbxsny9KKx5VFh",
		"csrfToken": "f9LLGYKAed2e.1596364716"
	},
```
Now you can get the next page [by performing a GET to their api](https://www.tumblr.com/api/v2/mobile/search/posts?fields[blogs]=name,avatar,title,url,is_adult,?is_member,description_npf,uuid,can_be_followed,?followed,?advertiser_name&reblog_info=true&mode=recent&query=car&limit=20&blog_limit=0&post_offset=1594857417&post_limit=20
) with the provided key and you'll get this json as response containing the posts of the next page:

[tumblr_tagged_search_api_results.txt](https://github.com/TumblThreeApp/TumblThree/files/5012023/tumblr_tagged_search_api_results.txt)

So, someone has to implement these 3 steps (perform a get to the initial search page, grep the json for the url and api token, perform a get to the next page(s)).

The good news is, the authentication seems to be still valid, Tumblr is kind enough to supply you with a valid api key, and for all these GET requests/greps etc, code is already there but mostly only has to be adjusted/modified.
I'm not sure if I am currently interested enough in this, probably not, hence if anyone wants to do this, this brief outline should help a lot.

**Comment by johanneszab** [comment]
This should also fix #69 (non-tagged tumblr searches).

**Comment by ErikBrown2** [comment]
Thanks for the reply and extensive explanation. Hopefully there will be somebody able to fix this. I will for now remove all the searches from my blog list.

**Comment by ErikBrown2** [comment]
Thank you very much for the fix. It works great again!

**Comment by johanneszab** [comment]
If someone is interested in download all the other post kinds (e.g. text/audio posts) when using the Tumblr tag search, it's really easy now that we have everything in json. Its only a couple lines of code (see the `tumblr_tagged_search_api_results.txt` from the second post above) and the [TumblrTagSearchCrawler](https://github.com/TumblThreeApp/TumblThree/blob/master/src/TumblThree/TumblThree.Applications/Crawler/TumblrTagSearchCrawler.cs).

video example
```json:
                "object_type": "post",
                "type": "blocks",
                "original_type": "video",

                "content": [{
                    "type": "video",
                    "provider": "youtube",
                    "url": "https://www.youtube.com/watch?v=qTtcohcNOws",
```

photo example:
```json
                "object_type": "post",
                "type": "blocks",
                "original_type": "photo",

                "content": [{
                    "type": "image",
                    "media": [{
                        "media_key": "11e3d41dc02524bb77b3c4a6ea4220d0:580b758f6fed98dd-37",
                        "type": "image/jpeg",
                        "width": 2048,
                        "height": 2731,
                        "url": "https://64.media.tumblr.com/11e3d41dc02524bb77b3c4a6ea4220d0/580b758f6fed98dd-37/s2048x3072/7210bd286c63ad3a34fa996bed0a746f83b8f37d.jpg",
```

It' all already mapped to a C# class.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
