### ISSUE TITLE
Best way to view results?

### ISSUE THREAD

**Issue by Shooter3k** [TumblThreeApp/TumblThree#84]
I must be missing something. What is the best way to view the results? 

Is a person supposed to view each file individually in something like Notepad++ and then manually look up the text and the picture that is attached with that post?

**Comment by thomas694** [comment]
The main purpose of this app is to make backups of blogs, so that in the rare event that shouldn't happen, you have all the media and its meta data of the blog. Of course you can view the media in window explorer and open it in any program you like. The backup is not supposed to be an exact offline copy with themes and same layout and so.

Up until now no one has made any suggestions what would be a good presentation of that data for viewing and checking the backup and/or has made any code contributions to implement it. Any contributions are welcome.

**Comment by kristofersokk** [comment]
For anyone wondering, I made a web-based application for viewing these blogs. For now, it only works in Chromium-based browsers.
It's open source, [Github](https://github.com/kristofersokk/local-tumbl-viewer)
It's deployed to [tumblviewer.app](https://tumblviewer.app/)
