### ISSUE TITLE
Crawl evaluates thousands of blogs

### ISSUE THREAD

**Issue by oDiDio** [TumblThreeApp/TumblThree#92]
Hi, 

I use TumblThree for over a year to save my favorites (liked by me). 
After updating to the new version I tried running it again but it just evaluates blogs.
Had it running overnight and at this moment it has evaluated just short of 80000 blogs.

Why is it doing this and is this normal? Never had this behaviour before.

Thanks for the help and the absolut cool programm.
![2020-09-30 13_54_16-Window](https://user-images.githubusercontent.com/58057146/94682173-db6d2000-0324-11eb-9418-f5c33200c09e.png)

**Comment by oDiDio** [comment]
I'm at over 140000 now. Gonna stop it. No idea what's going on.

**Comment by thomas694** [comment]
Can you confirm that it actually downloaded that amount of new blogs/files? I think it was running in an endless loop, downloading the same page over and over again and not even yet starting downloading any images.

**Comment by thomas694** [comment]
Since Tumblr's new privacy consent agreement and its cookies, the Liked/by crawler got stuck in an endless loop, because the .net's WebRequest cannot handle redirects that want to set cookies at the same time. Additionally they use a cookie value that .net cannot handle.
So now the redirects are done manually and the (broken) cookies are read with a custom parser.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
