### ISSUE TITLE
All Blogs gone/Cannot add anything new

### ISSUE THREAD

**Issue by SomeRandomDude870** [TumblThreeApp/TumblThree#97]
**Describe the bug**
Hi, I have populated the Program with several Blogs to download from and only downloaded a few of them. Now I start the program and there are no Blogs in it anymore.
Furthermore, I am unable to add new blogs to it.

Is there any way to get the blogs back? I still have the empty directories. Where is the database?
Also, I have tried it with the newest and there I am unable to add any blogs either.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - TumblThree version: 1.0.11.7 (yes, will update later)
 - OS: win10 pro
 - Browser Firefox
 - Version latest

**Additional context**

**Comment by thomas694** [comment]
Are you using it in normal or portable mode?
The blog settings/database files should be in an "Index" folder inside your chosen root folder (setting "Download location").

Has someone else experienced a similar problem?

**Comment by SomeRandomDude870** [comment]
Portable mode
There is no index folder in the Download folder but one in the program´s. 
There are only two tumblr files, one for the Settings and the other a single blogname. 
Can I just add the names of the generated folders to some settings to load the blogs?

**Comment by thomas694** [comment]
It sounds like your blogs root folder is set to the program's folder. You should change it by clicking Settings button, General tab, "Download location" field resp. Browse button and choose an independent folder. If you already have downloaded blogs, you can move their folders together with the Index folder to the new location.
Where did you extract the TumblThree zip file to, inside a protected folder (e.g. "C:\Program Files\")? For portable mode you should choose a folder outside of any protected folders, because the settings files and so on are written to the TumblThree folder, so your user needs write permission to that folder.

You can bulk import blogs by creating a text file with one blog url per line and loading it with the "Import Blog List" button. So a folder "abc" would belong to the blog url "https://abc.tumblr.com/".

**Comment by SomeRandomDude870** [comment]
No, it´s in an "normal" folder.
Well, I cannot add any blog to it :D :/

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
